#' @title Load_LGR
#'
#' @description Functions used to load raw data output from LGR Ultraportable Gas Analyzers to feed the function "FluxCal"
#'
#' @param file set "file" as raw data file name (may include the directory path, as string) WITHOUT changing anything
#' @param Time_format depending on the output timestamp, you may change into "dmy_hms" or "ymd_hms", default: "mdy_hms"
#'
#' @return a dataframe with all the loaded data in the right format
#'
#' @examples
#' # get the directory of the example raw data from LGR
#' example_data <- system.file("extdata", "gga17Feb2017_f0000.txt", package = "FluxCalR")
#' Flux <- Load_LGR(example_data) # input is a string with the directory of the data file and file name
#'
#' @export
## Function for loading data from LGR ----------
Load_LGR <- function(file, ## set "file" as raw data file name (as string) WITHOUT changing anything
                     Time_format="mdy_hms" ## depending on the output timestamp, you may change into "dmy_hms" or "ymd_hms"
){
  library(lubridate)
  # Load the raw data after deleting the text massages at the beginning and the end of each raw data file generate by LGR
  flux <- read.table(file, sep= ",", header = T,skip = 1,fill = T,stringsAsFactors = F)
  flux <- subset(flux,!is.na(flux[,2])) # remove the comments generated by LGR
  # replace the time with "lubridated" time with different format
  if (Time_format=="mdy_hms"){
    flux$Time <- mdy_hms(flux$Time)
  } else {
    if (Time_format=="dmy_hms"){
      flux$Time <- dmy_hms(flux$Time)
    } else {
      flux$Time <- ymd_hms(flux$Time) # with Time_format = "ymd_hms"
    }
  }
  return(flux)
}
##----------------------

#' @title Load_other
#'
#' @description Functions used to load raw data output from other similar analyzers (e.g. LICOR) to feed the function "FluxCal"
#'
#' @param file set "file" as raw data file name (may include the directory path, as string) WITHOUT changing anything
#' @param Time_format depending on the output timestamp, you may change into "dmy_hms" or "ymd_hms", default: "mdy_hms"
#' @param Date add the date of measurement in the format of "mm/dd/yyyy"
#' @param Time header name of the timestamps in the file (string)
#' @param CO2 header name of the CO2 concentrations in the file (string)
#' @param CH4 header name of the CH4 concentrations in the file (string). Default: no CH4 is measured
#' @param Ta header name of ambient air temperature in the file (string). If not measured, a constant value can be used. Default: 25 degree C
#' @param skip rows to be skipped at the beginning. Default: no rows will be skipped
#' @param sep delimiter to separate columns. Default: comma (",")
#'
#' @return a dataframe with all the loaded data in the right format
#'
#' @examples Flux <- Load_other("C:/Licor.txt",
#'                    Time_format = "hms",
#'                    Date = "5/11/2018",
#'                    Time = "time",
#'                    CO2 = "[co2]")
#'
#' @export
## Function for loading data from other sources ----------
Load_other <- function(file, ## set "file" as raw data file name (as string) WITHOUT changing anything
                       Time_format="mdy_hms", ## depending on the output timestamp, you may change into "dmy_hms" or "ymd_hms", or if only time is recorded use "hms"
                       Date = "1/31/2018", # add the date of measurement in the format of "mm/dd/yyyy"
                       Time = NA, # header name of the timestamps in the file (string)
                       CO2, # header name of the CO2 concentrations in the file (string)
                       CH4 = NA, # header name of the CH4 concentrations in the file (string). Default: no CH4 is measured
                       Ta = 25, # header name of ambient air temperature in the file (string). If not measured, a constant value can be used. Default: 25 degree C
                       skip = 0, # rows to be skipped at the beginning. Default: no rows will be skipped
                       sep = "," # delimiter to separate columns. Default: comma (",")
)
{
  library(lubridate)
  # Load the raw data after deleting the text massages at the beginning and the end of each raw data file generate by LGR
  flux <- read.table(file, sep= sep, header = T,skip = skip,fill = T,stringsAsFactors = F)
  flux <- subset(flux,!is.na(flux[,2])) # remove the comments generated by analyzer
  flux <- data.frame()
  # replace the time with "lubridated" time with different format
  if (Time_format=="mdy_hms"){
    flux$Time <- mdy_hms(flux[,Time])
  } else {
    if (Time_format=="dmy_hms"){
      flux$Time <- dmy_hms(flux[,Time])
    } else {
      if (Time_format=="ymd_hms"){
        flux$Time <- ymd_hms(flux[,Time]) # with Time_format = "ymd_hms"
      } else {
        Time <- paste0(Date,"_",flux[,Time]) # if only time is provided, then combine the time with date first
        flux$Time <- mdy_hms(Time)
      }
    }
  }

  flux$X.CO2.d_ppm <- flux[,CO2] # add a column as CO2 concentration with correct name
  # add a column as CH4 concentration
  if (is.na(CH4)){
    flux$X.CH4.d_ppm <- NA # create a column with NAs if CH4 is not measured
  } else {
    flux$X.CH4.d_ppm <- flux[,CH4]
  }
  # add a column as ambient air temperature
  if (is.string(Ta)){
    flux$AmbT_C <- flux[,Ta]
  } else {
    flux$AmbT_C <- Ta
  }

  return(flux)
}
