#' @title Load LGR data
#'
#' @description Function used to load raw data from LGR Ultraportable Gas Analyzers to feed the "data" argument in the function "FluxCal()".
#'
#' @param file A string contains the directory path and file name of the raw data. The data should be provided as what is exported from the LGR analyzer.
#' @param Time_format A string indicates the format of timestamps. Default: "mdy_hms". It can be changed into "dmy_hms" or "ymd_hms", depending on the data timestamps from the analyzer.
#'
#' @return A dataframe with all data in the right format for function "FluxCal()".
#'
#' @examples
#' # get the directory of the example LGR raw data
#' example_data <- system.file("extdata", "Flux_example_1_LGR.txt", package = "FluxCalR")
#' example_data
#' # load the data
#' Flux <- Load_LGR(example_data)
#'
#' @export
## Function for loading data from LGR ----------
Load_LGR <- function(file,
                     Time_format="mdy_hms"
){
  # Load the raw data after deleting the text massages at the beginning and the end of each raw data file generate by LGR
  flux <- read.table(file, sep= ",", header = TRUE,skip = 1,fill = TRUE,stringsAsFactors = FALSE)
  flux <- subset(flux,!is.na(flux[,2])) # remove the comments generated by LGR
  # replace the time with "lubridated" time with different format
  if (Time_format=="mdy_hms"){
    flux$Time <- lubridate::mdy_hms(flux$Time)
  } else {
    if (Time_format=="dmy_hms"){
      flux$Time <- lubridate::dmy_hms(flux$Time)
    } else {
      flux$Time <- lubridate::ymd_hms(flux$Time) # with Time_format = "ymd_hms"
    }
  }
  return(flux)
}
##----------------------

#' @title Load data from other analyzers
#'
#' @description Function used to load raw data output from other similar analyzers (e.g. LICOR) to feed the "data" argument in function "FluxCal()".
#'
#' @param file A string contains the directory path and file name of the raw data.
#' @param Time A string indicates column name of the timestamps in the data file.
#' @param Time_format A string indicates the format of timestamps. Default: "mdy_hms".
#' It can be changed into "dmy_hms" or "ymd_hms", depending on the data timestamp from the analyzer.
#' In case date and time are recorded separately, "hms" can be used here and add the date to the "Date" argument.
#' @param Date_ms A string indicates date of the measurements in the format of "mm/dd/yyyy". This argument is used only when date is not included in the timestamps.
#' @param CO2 A string indicates column name of the CO2 concentrations in the data file. Default: no CO2 is measured.
#' @param CH4 A string indicates column name of the CH4 concentrations in the data file. Default: no CH4 is measured.
#' @param Ta A string indicates column name of ambient air temperature in the data file. If not measured, a constant value can be used. Default: 25 degree C.
#' @param skip A number indicates rows to be skipped at the beginning of the data file. Default: 0, no rows will be skipped.
#' @param sep A string indicates delimiter that separates columns. Default: comma (",").
#' @param ... Other arguments used in the function "read.table()". See details *?read.table()*
#'
#' @return a dataframe with all data in the right format for function "FluxCal()".
#'
#' @examples
#' # get the directory of the example data
#' example_data <- system.file("extdata", "Flux_example_2_other.csv", package = "FluxCalR")
#' # load the data
#' Flux <- Load_other(example_data,
#'                    Time = "Date_time",
#'                    Time_format = "mdy_hms",
#'                    CO2 = "CO2_PPM",
#'                    Ta = "Tem_C")
#'
#' @export
## Function for loading data from other sources ----------
Load_other <- function(file,
                       Time,
                       Time_format="mdy_hms",
                       Date_ms = NULL,
                       CO2 = NULL,
                       CH4 = NULL,
                       Ta = 25,
                       skip = 0,
                       sep = ",",
                       ...
)
{
  # Load the raw data after deleting the text massages at the beginning and the end of each raw data file
  flux1 <- read.table(file, sep= sep, header = TRUE,skip = skip,fill = TRUE,stringsAsFactors = FALSE,...)
  flux1 <- subset(flux1,!is.na(flux1[,2])) # remove the comments generated by analyzer
  # replace the time with "lubridated" time with different format
  if (Time_format=="mdy_hms"){
    Time <- lubridate::mdy_hms(flux1[,Time])
  } else {
    if (Time_format=="dmy_hms"){
      Time <- lubridate::dmy_hms(flux1[,Time])
    } else {
      if (Time_format=="ymd_hms"){
        Time <- lubridate::ymd_hms(flux1[,Time]) # with Time_format = "ymd_hms"
      } else {
        Time <- paste0(Date_ms,"_",flux1[,Time]) # if only time is provided, then combine the time with date first
        Time <- lubridate::mdy_hms(Time)
      }
    }
  }
  # add a column as CO2 concentration
  if (is.null(CO2)){
    X.CO2.d_ppm <- NA # create a column with NAs if CO2 is not measured
  } else {
    X.CO2.d_ppm <- flux1[,CO2]
  }
  # add a column as CH4 concentration
  if (is.null(CH4)){
    X.CH4.d_ppm <- NA # create a column with NAs if CH4 is not measured
  } else {
    X.CH4.d_ppm <- flux1[,CH4]
  }
  # add a column as ambient air temperature
  if (assertthat::is.string(Ta)){
    AmbT_C <- flux1[,Ta]
  } else {
    AmbT_C <- Ta
  }
  flux <- data.frame(Time,X.CO2.d_ppm,X.CH4.d_ppm,AmbT_C)
  return(flux)
}
